Add transparent buffer around open panels
KittyCAD/modeling-app pull request #1485
Opened 2024-02-22 17:33 UTC by franknoirot

Adds a small transparent buffer to all open code panels using CSS and the `::before` pseudo-element so that users don't inadvertently interact with the stream when they intend to manipulate or select something in the pane.

@JBEmbedded discovered it was very easy to land right in the gutter to the left of the code pane when selecting text, and if you were in the middle of an action like drawing a line, the mouse-up from that selection would drop a segment point there.

You can't see the buffers normally but here they are highlighted:
![Screenshot 2024-02-22 at 12 33 08 PM](https://github.com/KittyCAD/modeling-app/assets/23481541/a04be135-1d7f-4185-a9c9-5ecd937105cf)

2024-02-22 19:04 UTC, Irev-Dev requested changes
Ahh sweet, I've closed #1484

I'm not actually sold on this

https://github.com/KittyCAD/modeling-app/assets/29681384/4070c8de-0015-4ba3-9537-19a1c1aca16e

2024-02-23 20:23 UTC, franknoirot commented
That's a great point @Irev-Dev, I'll try to make it more robust real quick

2024-02-23 20:31 UTC, franknoirot commented
lol the panels have `ml-5 my-5` and I set the buffers to be `-inset-4`. They just always need to match and I assumed it was `-4`

2024-02-26 03:26 UTC, Irev-Dev approved these changes
Oh cool, that makes sense!

The playwright test failure looked weird, which makes me think it's somehow related.
I've just run again in case, but if it fails again I can look into it.
It wasn't able to click the "clear button" which I'm guessing something shifted and that button is now covered by the code panel. if that's the case it will be an easy fix.

2024-02-26 04:14 UTC, Irev-Dev requested changes
https://github.com/KittyCAD/modeling-app/assets/29681384/acc76042-d82d-4a8b-a264-84311730b885

Playwright failure found a real regression, debug panel is bouncing all over the shop.

2024-02-26 15:11 UTC, franknoirot commented
Gah nice catch, that's a telltale sign of the margins overflowing. Sorry this little thing is a PITA, I'll make sure it's actually ready for your review next time

2024-04-02 13:56 UTC, franknoirot commented
I'm about to implement the new style of collapsible pane anyway so I'm just gonna close this

2024-04-02 13:56 UTC, closed without merging